# This is a basic workflow to help you get started with Actions +

name: CI

# Controls when the workflow will run
on:
  # 지정한 branch에서 push/pull_request 에 해당하는 command가 수행되면 이 workflow가 동작 합니다. 
  # 여기서는 간단히 main 브런치에서 push되면서 이 workflow가 실행 되도록 하겠습니다.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    
  
 
  # 이부분은 위의 trigger가 없어도 수동으로 동작 할 수 있게끔 해주는 역할을 합니다.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" ?-fd
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout release
      uses: actions/checkout@v3


    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

#     - name: archive drcloud
#       run: tar cvfz ./build-fe.tar.gz *

#    - name: zip 생성
#      run: zip -r ./build-fe.zip *
#      shell: bash
      
    - name: upload to S3
      run: aws s3 sync --region ap-northeast-2 ./ s3://alpha-model-repo/completion_model/
      
    - name: AWS SSM Send-Command
      # You may pin to the exact commit or the version.
      # uses: peterkimzz/aws-ssm-send-command@8d32fbc744c127490e85b29eefff09d40494fc86
      uses: peterkimzz/aws-ssm-send-command@v1.1.1
      with:
        # AWS access key id
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS secret access key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Where EC2 instance is
        aws-region: ap-northeast-2
        # AWS EC2 Instance id or ids
        instance-ids: i-0a5c39ee253881065
        # Bash command you want to execute
        command: sudo docker stop jolly_lichterman&& docker image prune -a&& aws s3 sync s3://alpha-model-repo/completion_model/ ./&& aws s3 sync s3://alpha-model-repo/model_weight/ /home/ubuntu/model/Model/&& docker build -t server&& docker run --name jolly_lichterman -p 8000:80 server
        # Command execution location
        working-directory: /home/ubuntu/model
        # Comment for Send-Command
        comment: AWS SSM Send-Command is ran


#     - name: Code Deploy
#       run: aws deploy create-deployment --application-name model-server-application --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name Model-Dev --s3-location bucket=alpha-model-repo,bundleType=tgz,key=model_server/build-fe.tar.gz
